import { Inter, DM_Sans, DM_Serif_Display } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/QueryProvider";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

const dm_sans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"], // light to extra bold and black
});

const dm_serif_display = DM_Serif_Display({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-dm-serif",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dm_sans.className} ${dm_serif_display.variable} bg-teal-950 pb-10`}>
      <QueryProvider>
        <Header />
        {children}
      </QueryProvider>
      </body>
    </html>
  );
}
